[package]
name = "cryptopals"
version = "0.1.0"
authors = ["Misha Zharov <mishazharov1@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.0"
base64 = "0.11.0"
openssl = "0.10.26"
